/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rabin;

/**
 *
 * @author Andre Simao
 */
public class RabinServidorEmitterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RabinFrame
     */
    public RabinServidorEmitterFrame() {
        initComponents();
        setSize(925, 610);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bitsRedundantsField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageEmittedArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageReceivedArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        timeEncryptField = new javax.swing.JTextField();
        encryptButton = new javax.swing.JButton();
        statusMessageLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusMessageMaxLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        maxMessageSizeField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("n:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 100, 40);

        bitsRedundantsField.setText("Default: 4 digits");
        getContentPane().add(bitsRedundantsField);
        bitsRedundantsField.setBounds(250, 450, 110, 30);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Public Key:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 20, 150, 40);

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Number of redundant bits:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 450, 230, 30);

        nField.setEnabled(false);
        getContentPane().add(nField);
        nField.setBounds(80, 70, 340, 40);

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Message to emit");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 120, 180, 40);

        messageEmittedArea.setColumns(20);
        messageEmittedArea.setRows(5);
        jScrollPane2.setViewportView(messageEmittedArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 160, 390, 220);

        messageReceivedArea1.setColumns(20);
        messageReceivedArea1.setRows(5);
        messageReceivedArea1.setEnabled(false);
        jScrollPane3.setViewportView(messageReceivedArea1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(470, 140, 420, 370);

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Message passed to receptor ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 60, 300, 40);

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Time to encrypht: ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(530, 510, 170, 40);

        timeEncryptField.setEnabled(false);
        getContentPane().add(timeEncryptField);
        timeEncryptField.setBounds(710, 520, 100, 30);

        encryptButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        encryptButton.setForeground(new java.awt.Color(0, 0, 255));
        encryptButton.setText("Encrypt!");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });
        getContentPane().add(encryptButton);
        encryptButton.setBounds(10, 410, 160, 40);

        statusMessageLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusMessageLabel.setText("status");
        getContentPane().add(statusMessageLabel);
        statusMessageLabel.setBounds(10, 390, 390, 20);

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel.setText("status bits redundants");
        getContentPane().add(statusLabel);
        statusLabel.setBounds(10, 480, 390, 20);

        statusMessageMaxLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusMessageMaxLabel.setForeground(new java.awt.Color(204, 204, 204));
        statusMessageMaxLabel.setText("message size status");
        getContentPane().add(statusMessageMaxLabel);
        statusMessageMaxLabel.setBounds(10, 540, 430, 20);

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Maximum message size");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 510, 220, 30);

        maxMessageSizeField.setText("Default: 10000 chars");
        getContentPane().add(maxMessageSizeField);
        maxMessageSizeField.setBounds(250, 510, 110, 30);

        connectButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        connectButton.setForeground(new java.awt.Color(0, 0, 255));
        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(connectButton);
        connectButton.setBounds(220, 400, 120, 37);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rabin/cryptographyBackGround2.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 920, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RabinServidorEmitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RabinServidorEmitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RabinServidorEmitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RabinServidorEmitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RabinServidorEmitterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JTextField bitsRedundantsField;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton encryptButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maxMessageSizeField;
    private javax.swing.JTextArea messageEmittedArea;
    private javax.swing.JTextArea messageReceivedArea1;
    private javax.swing.JTextField nField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JLabel statusMessageMaxLabel;
    private javax.swing.JTextField timeEncryptField;
    // End of variables declaration//GEN-END:variables
}
