
package Rabin;

public class RabinClienteReceptorFrame extends javax.swing.JFrame {

    /**
     * Creates new form RabinFrame
     */
    public RabinClienteReceptorFrame() {
        initComponents();
        setSize(925, 610);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        digiteQField = new javax.swing.JTextField();
        bitsRedundantsField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        digitePField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTranslatedArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        nField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageReceivedArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        timeTranslateField = new javax.swing.JTextField();
        translateButton = new javax.swing.JButton();
        statusPrivateKeysLabel = new javax.swing.JLabel();
        statusMessageLabel = new javax.swing.JLabel();
        xyLabel = new javax.swing.JLabel();
        xyField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        maxMessageSizeField = new javax.swing.JTextField();
        sendKeyButton = new javax.swing.JButton();
        connectButton = new javax.swing.JButton();
        statusConnectLabel = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("q:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 50, 60);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Message translated by receptor: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 230, 310, 40);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("n=p*q:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 330, 100, 40);

        digiteQField.setText("Digite q");
        getContentPane().add(digiteQField);
        digiteQField.setBounds(80, 140, 100, 30);

        bitsRedundantsField.setEnabled(false);
        getContentPane().add(bitsRedundantsField);
        bitsRedundantsField.setBounds(270, 440, 120, 30);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Public Key:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 270, 150, 40);

        digitePField.setText("Digite p");
        getContentPane().add(digitePField);
        digitePField.setBounds(80, 80, 100, 30);

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Number of redundant bits:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 440, 240, 30);

        messageTranslatedArea.setColumns(20);
        messageTranslatedArea.setRows(5);
        messageTranslatedArea.setEnabled(false);
        jScrollPane1.setViewportView(messageTranslatedArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 270, 450, 250);

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Private Keys:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 10, 170, 40);

        nField.setEnabled(false);
        getContentPane().add(nField);
        nField.setBounds(150, 340, 100, 30);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("p:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 50, 60);

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Time to translate: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(520, 520, 170, 40);

        messageReceivedArea1.setColumns(20);
        messageReceivedArea1.setRows(5);
        messageReceivedArea1.setEnabled(false);
        jScrollPane3.setViewportView(messageReceivedArea1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(450, 100, 450, 140);

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Message received:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(450, 50, 170, 40);

        timeTranslateField.setEnabled(false);
        getContentPane().add(timeTranslateField);
        timeTranslateField.setBounds(700, 530, 100, 30);

        translateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        translateButton.setForeground(new java.awt.Color(0, 0, 255));
        translateButton.setText("Translate!");
        translateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(translateButton);
        translateButton.setBounds(630, 50, 150, 31);

        statusPrivateKeysLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusPrivateKeysLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusPrivateKeysLabel.setText("status private keys");
        getContentPane().add(statusPrivateKeysLabel);
        statusPrivateKeysLabel.setBounds(30, 50, 370, 20);

        statusMessageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusMessageLabel.setText("status message");
        getContentPane().add(statusMessageLabel);
        statusMessageLabel.setBounds(450, 20, 310, 30);

        xyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xyLabel.setForeground(new java.awt.Color(204, 204, 204));
        xyLabel.setText("(x,y) with x*p+y*q=1 :");
        getContentPane().add(xyLabel);
        xyLabel.setBounds(30, 200, 180, 20);

        xyField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xyField.setEnabled(false);
        getContentPane().add(xyField);
        xyField.setBounds(230, 190, 150, 30);

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Maximum message size");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 500, 200, 30);

        maxMessageSizeField.setEnabled(false);
        getContentPane().add(maxMessageSizeField);
        maxMessageSizeField.setBounds(270, 500, 120, 30);

        sendKeyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendKeyButton.setForeground(new java.awt.Color(0, 0, 255));
        sendKeyButton.setText("Send Key!");
        sendKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendKeyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendKeyButton);
        sendKeyButton.setBounds(290, 330, 120, 40);

        connectButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        connectButton.setForeground(new java.awt.Color(0, 0, 255));
        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(connectButton);
        connectButton.setBounds(190, 270, 120, 40);

        statusConnectLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusConnectLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusConnectLabel.setText("status connection");
        getContentPane().add(statusConnectLabel);
        statusConnectLabel.setBounds(190, 240, 250, 20);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rabin/cryptographyBackGround2.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 910, 575);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void translateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_translateButtonActionPerformed

    private void sendKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendKeyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendKeyButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RabinClienteReceptorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RabinClienteReceptorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RabinClienteReceptorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RabinClienteReceptorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RabinClienteReceptorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JTextField bitsRedundantsField;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextField digitePField;
    private javax.swing.JTextField digiteQField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maxMessageSizeField;
    private javax.swing.JTextArea messageReceivedArea1;
    private javax.swing.JTextArea messageTranslatedArea;
    private javax.swing.JTextField nField;
    private javax.swing.JButton sendKeyButton;
    private javax.swing.JLabel statusConnectLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JLabel statusPrivateKeysLabel;
    private javax.swing.JTextField timeTranslateField;
    private javax.swing.JButton translateButton;
    private javax.swing.JTextField xyField;
    private javax.swing.JLabel xyLabel;
    // End of variables declaration//GEN-END:variables
}
