/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rabin;

/**
 *
 * @author Andre Simao
 */
public class RabinFrame extends javax.swing.JFrame {

    /**
     * Creates new form RabinFrame
     */
    public RabinFrame() {
        initComponents();
        setSize(925, 610);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        digiteQField = new javax.swing.JTextField();
        bitsRedundantsField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        digitePField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTranslatedArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        nField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageEmittedArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageReceivedArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        timeTranslateField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        timeInvasionField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        timeEncryptField = new javax.swing.JTextField();
        encryptButton = new javax.swing.JButton();
        statusPrivateKeysLabel = new javax.swing.JLabel();
        statusMessageLabel = new javax.swing.JLabel();
        xyLabel = new javax.swing.JLabel();
        xyField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusMessageMaxLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        maxMessageSizeField = new javax.swing.JTextField();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("q:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 50, 60);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Message translated by receptor: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 340, 310, 40);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("n=p*q:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 60, 100, 40);

        digiteQField.setText("Digite q");
        getContentPane().add(digiteQField);
        digiteQField.setBounds(80, 140, 100, 30);

        bitsRedundantsField.setText("Default: 4 digits");
        getContentPane().add(bitsRedundantsField);
        bitsRedundantsField.setBounds(230, 460, 120, 30);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Public Key:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 20, 150, 40);

        digitePField.setText("Digite p");
        getContentPane().add(digitePField);
        digitePField.setBounds(80, 80, 100, 30);

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Number of redundant bits:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 460, 200, 30);

        messageTranslatedArea.setColumns(20);
        messageTranslatedArea.setRows(5);
        messageTranslatedArea.setEnabled(false);
        jScrollPane1.setViewportView(messageTranslatedArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 390, 300, 140);

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Private Keys:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 10, 170, 40);

        nField.setEnabled(false);
        getContentPane().add(nField);
        nField.setBounds(530, 70, 100, 30);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("p:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 50, 60);

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Message with emitter:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 200, 240, 40);

        messageEmittedArea.setColumns(20);
        messageEmittedArea.setRows(5);
        jScrollPane2.setViewportView(messageEmittedArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 240, 310, 140);

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Time to translate: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(740, 450, 170, 40);

        messageReceivedArea1.setColumns(20);
        messageReceivedArea1.setRows(5);
        messageReceivedArea1.setEnabled(false);
        jScrollPane3.setViewportView(messageReceivedArea1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(420, 180, 300, 140);

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Message passed to receptor: ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(420, 130, 280, 40);

        timeTranslateField.setEnabled(false);
        getContentPane().add(timeTranslateField);
        timeTranslateField.setBounds(740, 500, 100, 30);

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Time to invasion:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(740, 20, 170, 40);

        timeInvasionField.setEnabled(false);
        getContentPane().add(timeInvasionField);
        timeInvasionField.setBounds(740, 70, 100, 30);

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Time to encrypht: ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(740, 240, 170, 40);

        timeEncryptField.setEnabled(false);
        getContentPane().add(timeEncryptField);
        timeEncryptField.setBounds(740, 290, 100, 30);

        encryptButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        encryptButton.setForeground(new java.awt.Color(0, 0, 255));
        encryptButton.setText("Encrypt!");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });
        getContentPane().add(encryptButton);
        encryptButton.setBounds(30, 420, 120, 37);

        statusPrivateKeysLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusPrivateKeysLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusPrivateKeysLabel.setText("status private keys");
        getContentPane().add(statusPrivateKeysLabel);
        statusPrivateKeysLabel.setBounds(30, 50, 370, 20);

        statusMessageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusMessageLabel.setText("status message");
        getContentPane().add(statusMessageLabel);
        statusMessageLabel.setBounds(30, 390, 310, 20);

        xyLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xyLabel.setForeground(new java.awt.Color(204, 204, 204));
        xyLabel.setText("(x,y) with x*p+y*q=1 :");
        getContentPane().add(xyLabel);
        xyLabel.setBounds(30, 180, 150, 20);

        xyField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xyField.setEnabled(false);
        getContentPane().add(xyField);
        xyField.setBounds(190, 180, 150, 20);

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel.setText("status bits redundants");
        getContentPane().add(statusLabel);
        statusLabel.setBounds(30, 490, 310, 20);

        statusMessageMaxLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusMessageMaxLabel.setForeground(new java.awt.Color(204, 204, 204));
        statusMessageMaxLabel.setText("message size status");
        getContentPane().add(statusMessageMaxLabel);
        statusMessageMaxLabel.setBounds(30, 540, 310, 20);

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Maximum message size");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 510, 200, 30);

        maxMessageSizeField.setText("Default: 10000 chars");
        getContentPane().add(maxMessageSizeField);
        maxMessageSizeField.setBounds(230, 510, 120, 30);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rabin/cryptographyBackGround2.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 910, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encryptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RabinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RabinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RabinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RabinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RabinFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JTextField bitsRedundantsField;
    private javax.swing.JTextField digitePField;
    private javax.swing.JTextField digiteQField;
    private javax.swing.JButton encryptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maxMessageSizeField;
    private javax.swing.JTextArea messageEmittedArea;
    private javax.swing.JTextArea messageReceivedArea1;
    private javax.swing.JTextArea messageTranslatedArea;
    private javax.swing.JTextField nField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JLabel statusMessageMaxLabel;
    private javax.swing.JLabel statusPrivateKeysLabel;
    private javax.swing.JTextField timeEncryptField;
    private javax.swing.JTextField timeInvasionField;
    private javax.swing.JTextField timeTranslateField;
    private javax.swing.JTextField xyField;
    private javax.swing.JLabel xyLabel;
    // End of variables declaration//GEN-END:variables
}
